name: Pull Request

on: pull_request

env:
  CI: true

jobs:
  check:
    name: Checklist
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: npm ci

      - name: Affected Build
        run: npx nx affected:build

      - name: Affected Release
        run: npx nx affected --target release
