name: Pull Request

on: pull_request

env:
  CI: true

jobs:
  check:
    name: Checklist
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - uses: mansagroup/nrwl-nx-action@v2
        with:
          targets: lint,test,build,release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
