name: Push Release

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  release:
    name: Build, Release & Publish
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Dependencies
        run: npm ci

      - name: Check Format
        run: npm run format

      - name: Lint Workspace & Code
        run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: Build, Release on GitHub & Publish to NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
